//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 09:06:03 PM BST 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tDecisionTable complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDecisionTable"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tExpression"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="input" type="{http://www.omg.org/spec/DMN/20130901}tDTInput" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element name="output" type="{http://www.omg.org/spec/DMN/20130901}tDTOutput" maxOccurs="unbounded"/&gt;
 *         &lt;element name="rule" type="{http://www.omg.org/spec/DMN/20130901}tDecisionRule" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="hitPolicy" type="{http://www.omg.org/spec/DMN/20130901}HitPolicy" default="UNIQUE" /&gt;
 *       &lt;attribute name="aggregation" type="{http://www.omg.org/spec/DMN/20130901}BuiltinAggregator" /&gt;
 *       &lt;attribute name="preferedOrientation" type="{http://www.omg.org/spec/DMN/20130901}DecisionTableOrientation" default="Rule-as-Row" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDecisionTable", propOrder = {
    "inputs",
    "outputs",
    "rules"
})
public class DecisionTable
    extends Expression
    implements Serializable
{

    @XmlElement(name = "input")
    protected List<DtInput> inputs;
    @XmlElement(name = "output", required = true)
    protected List<DtOutput> outputs;
    @XmlElement(name = "rule")
    protected List<DecisionRule> rules;
    @XmlAttribute(name = "hitPolicy")
    protected HitPolicy hitPolicy;
    @XmlAttribute(name = "aggregation")
    protected BuiltinAggregator aggregation;
    @XmlAttribute(name = "preferedOrientation")
    protected DecisionTableOrientation preferedOrientation;

    /**
     * Gets the value of the inputs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DtInput }
     * 
     * 
     */
    public List<DtInput> getInputs() {
        if (inputs == null) {
            inputs = new ArrayList<DtInput>();
        }
        return this.inputs;
    }

    /**
     * Gets the value of the outputs property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the outputs property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOutputs().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DtOutput }
     * 
     * 
     */
    public List<DtOutput> getOutputs() {
        if (outputs == null) {
            outputs = new ArrayList<DtOutput>();
        }
        return this.outputs;
    }

    /**
     * Gets the value of the rules property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the rules property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getRules().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link DecisionRule }
     * 
     * 
     */
    public List<DecisionRule> getRules() {
        if (rules == null) {
            rules = new ArrayList<DecisionRule>();
        }
        return this.rules;
    }

    /**
     * Gets the value of the hitPolicy property.
     * 
     * @return
     *     possible object is
     *     {@link HitPolicy }
     *     
     */
    public HitPolicy getHitPolicy() {
        if (hitPolicy == null) {
            return HitPolicy.UNIQUE;
        } else {
            return hitPolicy;
        }
    }

    /**
     * Sets the value of the hitPolicy property.
     * 
     * @param value
     *     allowed object is
     *     {@link HitPolicy }
     *     
     */
    public void setHitPolicy(HitPolicy value) {
        this.hitPolicy = value;
    }

    /**
     * Gets the value of the aggregation property.
     * 
     * @return
     *     possible object is
     *     {@link BuiltinAggregator }
     *     
     */
    public BuiltinAggregator getAggregation() {
        return aggregation;
    }

    /**
     * Sets the value of the aggregation property.
     * 
     * @param value
     *     allowed object is
     *     {@link BuiltinAggregator }
     *     
     */
    public void setAggregation(BuiltinAggregator value) {
        this.aggregation = value;
    }

    /**
     * Gets the value of the preferedOrientation property.
     * 
     * @return
     *     possible object is
     *     {@link DecisionTableOrientation }
     *     
     */
    public DecisionTableOrientation getPreferedOrientation() {
        if (preferedOrientation == null) {
            return DecisionTableOrientation.RULE_AS_ROW;
        } else {
            return preferedOrientation;
        }
    }

    /**
     * Sets the value of the preferedOrientation property.
     * 
     * @param value
     *     allowed object is
     *     {@link DecisionTableOrientation }
     *     
     */
    public void setPreferedOrientation(DecisionTableOrientation value) {
        this.preferedOrientation = value;
    }

    public DecisionTable withInputs(DtInput... values) {
        if (values!= null) {
            for (DtInput value: values) {
                getInputs().add(value);
            }
        }
        return this;
    }

    public DecisionTable withInputs(Collection<DtInput> values) {
        if (values!= null) {
            getInputs().addAll(values);
        }
        return this;
    }

    public DecisionTable withOutputs(DtOutput... values) {
        if (values!= null) {
            for (DtOutput value: values) {
                getOutputs().add(value);
            }
        }
        return this;
    }

    public DecisionTable withOutputs(Collection<DtOutput> values) {
        if (values!= null) {
            getOutputs().addAll(values);
        }
        return this;
    }

    public DecisionTable withRules(DecisionRule... values) {
        if (values!= null) {
            for (DecisionRule value: values) {
                getRules().add(value);
            }
        }
        return this;
    }

    public DecisionTable withRules(Collection<DecisionRule> values) {
        if (values!= null) {
            getRules().addAll(values);
        }
        return this;
    }

    public DecisionTable withHitPolicy(HitPolicy value) {
        setHitPolicy(value);
        return this;
    }

    public DecisionTable withAggregation(BuiltinAggregator value) {
        setAggregation(value);
        return this;
    }

    public DecisionTable withPreferedOrientation(DecisionTableOrientation value) {
        setPreferedOrientation(value);
        return this;
    }

    @Override
    public DecisionTable withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DecisionTable withAnys(Element... values) {
        if (values!= null) {
            for (Element value: values) {
                getAnys().add(value);
            }
        }
        return this;
    }

    @Override
    public DecisionTable withAnys(Collection<Element> values) {
        if (values!= null) {
            getAnys().addAll(values);
        }
        return this;
    }

    @Override
    public DecisionTable withId(String value) {
        setId(value);
        return this;
    }

}
