//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 09:06:03 PM BST 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;
import java.util.Collection;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.bind.annotation.XmlType;

import org.w3c.dom.Element;


/**
 * <p>Java class for tDRGElement complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDRGElement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tNamedElement"&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDRGElement")
@XmlSeeAlso({
    Decision.class,
    BusinessKnowledgeModel.class,
    InputData.class,
    KnowledgeSource.class
})
public class DrgElement extends NamedElement implements Serializable {

    @Override
    public DrgElement withName(String value) {
        setName(value);
        return this;
    }

    @Override
    public DrgElement withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public DrgElement withAnys(Element... values) {
        if (values!= null) {
            for (Element value: values) {
                getAnys().add(value);
            }
        }
        return this;
    }

    @Override
    public DrgElement withAnys(Collection<Element> values) {
        if (values!= null) {
            getAnys().addAll(values);
        }
        return this;
    }

    @Override
    public DrgElement withId(String value) {
        setId(value);
        return this;
    }

}
