//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 09:06:03 PM BST 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDTInput complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tDTInput"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tClause"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="inputExpression" type="{http://www.omg.org/spec/DMN/20130901}tLiteralExpression"/&gt;
 *         &lt;element name="inputValue" type="{http://www.omg.org/spec/DMN/20130901}tLiteralExpression" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tDTInput", propOrder = {
    "inputExpression",
    "inputValues"
})
public class DtInput
    extends Clause
    implements Serializable
{

    @XmlElement(required = true)
    protected LiteralExpression inputExpression;
    @XmlElement(name = "inputValue")
    protected List<LiteralExpression> inputValues;

    /**
     * Gets the value of the inputExpression property.
     * 
     * @return
     *     possible object is
     *     {@link LiteralExpression }
     *     
     */
    public LiteralExpression getInputExpression() {
        return inputExpression;
    }

    /**
     * Sets the value of the inputExpression property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiteralExpression }
     *     
     */
    public void setInputExpression(LiteralExpression value) {
        this.inputExpression = value;
    }

    /**
     * Gets the value of the inputValues property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the inputValues property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getInputValues().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link LiteralExpression }
     * 
     * 
     */
    public List<LiteralExpression> getInputValues() {
        if (inputValues == null) {
            inputValues = new ArrayList<LiteralExpression>();
        }
        return this.inputValues;
    }

    public DtInput withInputExpression(LiteralExpression value) {
        setInputExpression(value);
        return this;
    }

    public DtInput withInputValues(LiteralExpression... values) {
        if (values!= null) {
            for (LiteralExpression value: values) {
                getInputValues().add(value);
            }
        }
        return this;
    }

    public DtInput withInputValues(Collection<LiteralExpression> values) {
        if (values!= null) {
            getInputValues().addAll(values);
        }
        return this;
    }

    @Override
    public DtInput withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public DtInput withName(String value) {
        setName(value);
        return this;
    }

}
