//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:30:38 PM GMT 
//


package io.onedecision.engine.decisions.model.dmn;

import io.onedecision.engine.decisions.api.DecisionConstants;

import java.io.Serializable;
import java.util.ArrayList;
import java.util.Collection;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>
 * Java class for tFunctionDefinition complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tFunctionDefinition"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20151101/dmn.xsd}tExpression"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="formalParameter" type="{http://www.omg.org/spec/DMN/20151101/dmn.xsd}tInformationItem" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.omg.org/spec/DMN/20151101/dmn.xsd}expression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tFunctionDefinition", propOrder = {
    "formalParameter",
    "expression"
})
public class FunctionDefinition extends Expression implements Serializable {

    private static final long serialVersionUID = -8208911742535485516L;
    private static final ObjectFactory objFact = new ObjectFactory();
    protected java.util.List<InformationItem> formalParameter;
    @XmlElementRef(name = "expression", namespace = "http://www.omg.org/spec/DMN/20151101/dmn.xsd", type = JAXBElement.class, required = false)
    protected JAXBElement<? extends Expression> expression;

    /**
     * Gets the value of the formalParameter property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the formalParameter property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getFormalParameter().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link InformationItem }
     * 
     * 
     */
    public java.util.List<InformationItem> getFormalParameters() {
        if (formalParameter == null) {
            formalParameter = new ArrayList<InformationItem>();
        }
        return this.formalParameter;
    }

    /**
     * Gets the value of the expression property.
     * 
     * @return
     *     possible object is
     *     {@link JAXBElement }{@code <}{@link FunctionDefinition }{@code >}
     *     {@link JAXBElement }{@code <}{@link DecisionTable }{@code >}
     *     {@link JAXBElement }{@code <}{@link Invocation }{@code >}
     *     {@link JAXBElement }{@code <}{@link LiteralExpression }{@code >}
     *     {@link JAXBElement }{@code <}{@link io.onedecision.engine.decisions.model.dmn.List }{@code >}
     *     {@link JAXBElement }{@code <}{@link Context }{@code >}
     *     {@link JAXBElement }{@code <}{@link Expression }{@code >}
     *     {@link JAXBElement }{@code <}{@link Relation }{@code >}
     *     
     */
    public JAXBElement<? extends Expression> getExpression() {
        return expression;
    }

    /**
     * Sets the value of the expression property.
     * 
     * @param value
     *     allowed object is
     *     {@link JAXBElement }{@code <}{@link FunctionDefinition }{@code >}
     *     {@link JAXBElement }{@code <}{@link DecisionTable }{@code >}
     *     {@link JAXBElement }{@code <}{@link Invocation }{@code >}
     *     {@link JAXBElement }{@code <}{@link LiteralExpression }{@code >}
     *     {@link JAXBElement }{@code <}{@link io.onedecision.engine.decisions.model.dmn.List }{@code >}
     *     {@link JAXBElement }{@code <}{@link Context }{@code >}
     *     {@link JAXBElement }{@code <}{@link Expression }{@code >}
     *     {@link JAXBElement }{@code <}{@link Relation }{@code >}
     *     
     */
    public void setExpression(JAXBElement<? extends Expression> value) {
        this.expression = value;
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void setDecisionTable(DecisionTable dt) {
        setExpression(new JAXBElement(DecisionConstants.DECISION_TABLE,
                DecisionTable.class, dt));
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void setContext(Context ctxt) {
        setExpression(new JAXBElement(DecisionConstants.CONTEXT, Context.class,
                ctxt));
    }

    @SuppressWarnings({ "rawtypes", "unchecked" })
    public void setLiteralExpression(LiteralExpression le) {
        setExpression(new JAXBElement(DecisionConstants.LITERAL_EXPRESSION,
                LiteralExpression.class, le));
    }

    public FunctionDefinition withFormalParameter(String name, QName type) {
        InformationItem item = objFact.createInformationItem().withName(name)
                .withTypeRef(type);
        return withFormalParameter(item);
    }

    public FunctionDefinition withFormalParameter(InformationItem item) {
        getFormalParameters().add(item);
        return this;
    }

    public FunctionDefinition withFormalParameters(InformationItem... values) {
        if (values!= null) {
            for (InformationItem value: values) {
                getFormalParameters().add(value);
            }
        }
        return this;
    }

    public FunctionDefinition withFormalParameters(Collection<InformationItem> values) {
        if (values!= null) {
            getFormalParameters().addAll(values);
        }
        return this;
    }

    public FunctionDefinition withExpression(JAXBElement<? extends Expression> value) {
        setExpression(value);
        return this;
    }

    public FunctionDefinition withLiteralExpression(String text) {
        setLiteralExpression(objFact.createLiteralExpression().withText(text));
        return this;
    }

    public FunctionDefinition withDecisionTable(DecisionTable value) {
        setDecisionTable(value);
        return this;
    }

    public FunctionDefinition withContext(Context ctxt) {
        setContext(ctxt);
        return this;
    }

    @Override
    public FunctionDefinition withTypeRef(QName value) {
        setTypeRef(value);
        return this;
    }

    @Override
    public FunctionDefinition withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public FunctionDefinition withExtensionElements(io.onedecision.engine.decisions.model.dmn.DmnElement.ExtensionElements value) {
        setExtensionElements(value);
        return this;
    }

    @Override
    public FunctionDefinition withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public FunctionDefinition withLabel(String value) {
        setLabel(value);
        return this;
    }

}
