//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:30:38 PM GMT 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tImportedValues complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tImportedValues"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tImport"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="importedElement" type="{http://www.w3.org/2001/XMLSchema}string"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="expressionLanguage" type="{http://www.w3.org/2001/XMLSchema}anyURI" /&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tImportedValues", propOrder = {
    "importedElement"
})
public class ImportedValues
    extends Import
    implements Serializable
{

    @XmlElement(required = true)
    protected String importedElement;
    @XmlAttribute(name = "expressionLanguage")
    @XmlSchemaType(name = "anyURI")
    protected String expressionLanguage;

    /**
     * Gets the value of the importedElement property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getImportedElement() {
        return importedElement;
    }

    /**
     * Sets the value of the importedElement property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setImportedElement(String value) {
        this.importedElement = value;
    }

    /**
     * Gets the value of the expressionLanguage property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getExpressionLanguage() {
        return expressionLanguage;
    }

    /**
     * Sets the value of the expressionLanguage property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setExpressionLanguage(String value) {
        this.expressionLanguage = value;
    }

    public ImportedValues withImportedElement(String value) {
        setImportedElement(value);
        return this;
    }

    public ImportedValues withExpressionLanguage(String value) {
        setExpressionLanguage(value);
        return this;
    }

    @Override
    public ImportedValues withNamespace(String value) {
        setNamespace(value);
        return this;
    }

    @Override
    public ImportedValues withLocationURI(String value) {
        setLocationURI(value);
        return this;
    }

    @Override
    public ImportedValues withImportType(String value) {
        setImportType(value);
        return this;
    }

}
