//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 04:59:26 PM BST 
//


package io.onedecision.engine.decisions.model.dmn;

import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tInformationItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tInformationItem"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tNamedElement"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="itemDefinition" type="{http://www.omg.org/spec/DMN/20130901}tDMNElementReference" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInformationItem", propOrder = {
    "itemDefinition"
})
public class InformationItem
    extends NamedElement
{

    protected DmnElementReference itemDefinition;

    /**
     * Gets the value of the itemDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link DmnElementReference }
     *     
     */
    public DmnElementReference getItemDefinition() {
        return itemDefinition;
    }

    /**
     * Sets the value of the itemDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmnElementReference }
     *     
     */
    public void setItemDefinition(DmnElementReference value) {
        this.itemDefinition = value;
    }

    public InformationItem withItemDefinition(DmnElementReference value) {
        setItemDefinition(value);
        return this;
    }

    @Override
    public InformationItem withName(String value) {
        setName(value);
        return this;
    }

    @Override
    public InformationItem withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public InformationItem withAny(Object... values) {
        if (values!= null) {
            for (Object value: values) {
                getAny().add(value);
            }
        }
        return this;
    }

    @Override
    public InformationItem withAny(Collection<Object> values) {
        if (values!= null) {
            getAny().addAll(values);
        }
        return this;
    }

    @Override
    public InformationItem withId(String value) {
        setId(value);
        return this;
    }

}
