//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 09:06:03 PM BST 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;
import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import org.w3c.dom.Element;


/**
 * <p>Java class for tInputData complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tInputData"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tDRGElement"&gt;
 *       &lt;sequence&gt;
 *         &lt;element ref="{http://www.omg.org/spec/DMN/20130901}InformationItem" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInputData", propOrder = {
    "informationItem"
})
public class InputData
    extends DrgElement
    implements Serializable
{

    @XmlElement(name = "InformationItem")
    protected InformationItem informationItem;

    /**
     * Gets the value of the informationItem property.
     * 
     * @return
     *     possible object is
     *     {@link InformationItem }
     *     
     */
    public InformationItem getInformationItem() {
        return informationItem;
    }

    /**
     * Sets the value of the informationItem property.
     * 
     * @param value
     *     allowed object is
     *     {@link InformationItem }
     *     
     */
    public void setInformationItem(InformationItem value) {
        this.informationItem = value;
    }

    public InputData withInformationItem(InformationItem value) {
        setInformationItem(value);
        return this;
    }

    @Override
    public InputData withName(String value) {
        setName(value);
        return this;
    }

    @Override
    public InputData withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public InputData withAnies(Element... values) {
        if (values!= null) {
            for (Element value: values) {
                getAnies().add(value);
            }
        }
        return this;
    }

    @Override
    public InputData withAnies(Collection<Element> values) {
        if (values!= null) {
            getAnies().addAll(values);
        }
        return this;
    }

    @Override
    public InputData withId(String value) {
        setId(value);
        return this;
    }

}
