//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:30:38 PM GMT 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>
 * Java class for tKnowledgeRequirement complex type.
 * 
 * <p>
 * The following schema fragment specifies the expected content contained within
 * this class.
 * 
 * <pre>
 * &lt;complexType name="tKnowledgeRequirement"&gt;
 *   &lt;complexContent&gt;
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="requiredKnowledge" type="{http://www.omg.org/spec/DMN/20151101/dmn.xsd}tDMNElementReference"/&gt;
 *       &lt;/sequence&gt;
 *     &lt;/restriction&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tKnowledgeRequirement", propOrder = {
    "requiredKnowledge"
})
public class KnowledgeRequirement implements Serializable {
    
    private static final long serialVersionUID = 2530153503900320633L;

    private static ObjectFactory objFact = new ObjectFactory();

    @XmlElement(required = true)
    protected DmnElementReference requiredKnowledge;

    /**
     * Gets the value of the requiredKnowledge property.
     * 
     * @return
     *     possible object is
     *     {@link DmnElementReference }
     *     
     */
    public DmnElementReference getRequiredKnowledge() {
        return requiredKnowledge;
    }

    /**
     * Sets the value of the requiredKnowledge property.
     * 
     * @param value
     *     allowed object is
     *     {@link DmnElementReference }
     *     
     */
    public void setRequiredKnowledge(DmnElementReference value) {
        this.requiredKnowledge = value;
    }

    public KnowledgeRequirement withRequiredKnowledge(DmnElementReference value) {
        setRequiredKnowledge(value);
        return this;
    }

    public KnowledgeRequirement withRequiredKnowledge(
            BusinessKnowledgeModel value) {
        setRequiredKnowledge(objFact.createDmnElementReference().withHref(
                value.getId()));
        return this;
    }

}
