//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:30:38 PM GMT 
//


package io.onedecision.engine.decisions.model.dmn;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the io.onedecision.engine.decisions.model.dmn package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _DMNElement_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "DMNElement");
    private final static QName _NamedElement_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "namedElement");
    private final static QName _Definitions_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "definitions");
    private final static QName _Import_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "import");
    private final static QName _ElementCollection_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "elementCollection");
    private final static QName _DrgElement_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "drgElement");
    private final static QName _Decision_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "decision");
    private final static QName _BusinessContextElement_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "businessContextElement");
    private final static QName _PerformanceIndicator_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "performanceIndicator");
    private final static QName _OrganizationUnit_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "organizationUnit");
    private final static QName _BusinessKnowledgeModel_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "businessKnowledgeModel");
    private final static QName _InputData_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "inputData");
    private final static QName _KnowledgeSource_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "knowledgeSource");
    private final static QName _Expression_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "expression");
    private final static QName _ItemDefinition_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "itemDefinition");
    private final static QName _LiteralExpression_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "literalExpression");
    private final static QName _Invocation_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "invocation");
    private final static QName _InformationItem_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "informationItem");
    private final static QName _DecisionTable_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "decisionTable");
    private final static QName _Artifact_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "artifact");
    private final static QName _TextAnnotation_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "textAnnotation");
    private final static QName _Association_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "association");
    private final static QName _Context_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "context");
    private final static QName _FunctionDefinition_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "functionDefinition");
    private final static QName _Relation_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "relation");
    private final static QName _List_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "list");
    private final static QName _DecisionService_QNAME = new QName("http://www.omg.org/spec/DMN/20130901", "decisionService");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: io.onedecision.engine.decisions.model.dmn
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link DmnElement }
     * 
     */
    public DmnElement createDmnElement() {
        return new DmnElement();
    }

    /**
     * Create an instance of {@link NamedElement }
     * 
     */
    public NamedElement createNamedElement() {
        return new NamedElement();
    }

    /**
     * Create an instance of {@link Definitions }
     * 
     */
    public Definitions createDefinitions() {
        return new Definitions();
    }

    /**
     * Create an instance of {@link Import }
     * 
     */
    public Import createImport() {
        return new Import();
    }

    /**
     * Create an instance of {@link ElementCollection }
     * 
     */
    public ElementCollection createElementCollection() {
        return new ElementCollection();
    }

    /**
     * Create an instance of {@link DrgElement }
     * 
     */
    public DrgElement createDrgElement() {
        return new DrgElement();
    }

    /**
     * Create an instance of {@link Decision }
     * 
     */
    public Decision createDecision() {
        return new Decision();
    }

    /**
     * Create an instance of {@link BusinessContextElement }
     * 
     */
    public BusinessContextElement createBusinessContextElement() {
        return new BusinessContextElement();
    }

    /**
     * Create an instance of {@link PerformanceIndicator }
     * 
     */
    public PerformanceIndicator createPerformanceIndicator() {
        return new PerformanceIndicator();
    }

    /**
     * Create an instance of {@link OrganizationUnit }
     * 
     */
    public OrganizationUnit createOrganizationUnit() {
        return new OrganizationUnit();
    }

    /**
     * Create an instance of {@link BusinessKnowledgeModel }
     * 
     */
    public BusinessKnowledgeModel createBusinessKnowledgeModel() {
        return new BusinessKnowledgeModel();
    }

    /**
     * Create an instance of {@link InputData }
     * 
     */
    public InputData createInputData() {
        return new InputData();
    }

    /**
     * Create an instance of {@link KnowledgeSource }
     * 
     */
    public KnowledgeSource createKnowledgeSource() {
        return new KnowledgeSource();
    }

    /**
     * Create an instance of {@link Expression }
     * 
     */
    public Expression createExpression() {
        return new Expression();
    }

    /**
     * Create an instance of {@link ItemDefinition }
     * 
     */
    public ItemDefinition createItemDefinition() {
        return new ItemDefinition();
    }

    /**
     * Create an instance of {@link LiteralExpression }
     * 
     */
    public LiteralExpression createLiteralExpression() {
        return new LiteralExpression();
    }

    /**
     * Create an instance of {@link Invocation }
     * 
     */
    public Invocation createInvocation() {
        return new Invocation();
    }

    /**
     * Create an instance of {@link InformationItem }
     * 
     */
    public InformationItem createInformationItem() {
        return new InformationItem();
    }

    /**
     * Create an instance of {@link DecisionTable }
     * 
     */
    public DecisionTable createDecisionTable() {
        return new DecisionTable();
    }

    /**
     * Create an instance of {@link Artifact }
     * 
     */
    public Artifact createArtifact() {
        return new Artifact();
    }

    /**
     * Create an instance of {@link TextAnnotation }
     * 
     */
    public TextAnnotation createTextAnnotation() {
        return new TextAnnotation();
    }

    /**
     * Create an instance of {@link Association }
     * 
     */
    public Association createAssociation() {
        return new Association();
    }

    /**
     * Create an instance of {@link Context }
     * 
     */
    public Context createContext() {
        return new Context();
    }

    /**
     * Create an instance of {@link FunctionDefinition }
     * 
     */
    public FunctionDefinition createFunctionDefinition() {
        return new FunctionDefinition();
    }

    /**
     * Create an instance of {@link Relation }
     * 
     */
    public Relation createRelation() {
        return new Relation();
    }

    /**
     * Create an instance of {@link List }
     * 
     */
    public List createList() {
        return new List();
    }

    /**
     * Create an instance of {@link DecisionService }
     * 
     */
    public DecisionService createDecisionService() {
        return new DecisionService();
    }

    /**
     * Create an instance of {@link DmnElementReference }
     * 
     */
    public DmnElementReference createDmnElementReference() {
        return new DmnElementReference();
    }

    /**
     * Create an instance of {@link InformationRequirement }
     * 
     */
    public InformationRequirement createInformationRequirement() {
        return new InformationRequirement();
    }

    /**
     * Create an instance of {@link KnowledgeRequirement }
     * 
     */
    public KnowledgeRequirement createKnowledgeRequirement() {
        return new KnowledgeRequirement();
    }

    /**
     * Create an instance of {@link AuthorityRequirement }
     * 
     */
    public AuthorityRequirement createAuthorityRequirement() {
        return new AuthorityRequirement();
    }

    /**
     * Create an instance of {@link Binding }
     * 
     */
    public Binding createBinding() {
        return new Binding();
    }

    /**
     * Create an instance of {@link DecisionRule }
     * 
     */
    public DecisionRule createDecisionRule() {
        return new DecisionRule();
    }

    /**
     * Create an instance of {@link ImportedValues }
     * 
     */
    public ImportedValues createImportedValues() {
        return new ImportedValues();
    }

    /**
     * Create an instance of {@link OutputClause }
     * 
     */
    public OutputClause createOutputClause() {
        return new OutputClause();
    }

    /**
     * Create an instance of {@link InputClause }
     * 
     */
    public InputClause createInputClause() {
        return new InputClause();
    }

    /**
     * Create an instance of {@link ContextEntry }
     * 
     */
    public ContextEntry createContextEntry() {
        return new ContextEntry();
    }

    /**
     * Create an instance of {@link UnaryTests }
     * 
     */
    public UnaryTests createUnaryTests() {
        return new UnaryTests();
    }

    /**
     * Create an instance of {@link DmnElement.ExtensionElements }
     * 
     */
    public DmnElement.ExtensionElements createDmnElementExtensionElements() {
        return new DmnElement.ExtensionElements();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DmnElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "DMNElement")
    public JAXBElement<DmnElement> createDMNElement(DmnElement value) {
        return new JAXBElement<DmnElement>(_DMNElement_QNAME, DmnElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link NamedElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "namedElement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "DMNElement")
    public JAXBElement<NamedElement> createNamedElement(NamedElement value) {
        return new JAXBElement<NamedElement>(_NamedElement_QNAME, NamedElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Definitions }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "definitions", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "namedElement")
    public JAXBElement<Definitions> createDefinitions(Definitions value) {
        return new JAXBElement<Definitions>(_Definitions_QNAME, Definitions.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Import }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "import")
    public JAXBElement<Import> createImport(Import value) {
        return new JAXBElement<Import>(_Import_QNAME, Import.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ElementCollection }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "elementCollection", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "namedElement")
    public JAXBElement<ElementCollection> createElementCollection(ElementCollection value) {
        return new JAXBElement<ElementCollection>(_ElementCollection_QNAME, ElementCollection.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DrgElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "drgElement", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "namedElement")
    public JAXBElement<DrgElement> createDrgElement(DrgElement value) {
        return new JAXBElement<DrgElement>(_DrgElement_QNAME, DrgElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Decision }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "decision", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "drgElement")
    public JAXBElement<Decision> createDecision(Decision value) {
        return new JAXBElement<Decision>(_Decision_QNAME, Decision.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessContextElement }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "businessContextElement")
    public JAXBElement<BusinessContextElement> createBusinessContextElement(BusinessContextElement value) {
        return new JAXBElement<BusinessContextElement>(_BusinessContextElement_QNAME, BusinessContextElement.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link PerformanceIndicator }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "performanceIndicator", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "businessContextElement")
    public JAXBElement<PerformanceIndicator> createPerformanceIndicator(PerformanceIndicator value) {
        return new JAXBElement<PerformanceIndicator>(_PerformanceIndicator_QNAME, PerformanceIndicator.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OrganizationUnit }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "organizationUnit", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "businessContextElement")
    public JAXBElement<OrganizationUnit> createOrganizationUnit(OrganizationUnit value) {
        return new JAXBElement<OrganizationUnit>(_OrganizationUnit_QNAME, OrganizationUnit.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link BusinessKnowledgeModel }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "businessKnowledgeModel", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "drgElement")
    public JAXBElement<BusinessKnowledgeModel> createBusinessKnowledgeModel(BusinessKnowledgeModel value) {
        return new JAXBElement<BusinessKnowledgeModel>(_BusinessKnowledgeModel_QNAME, BusinessKnowledgeModel.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InputData }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "inputData", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "drgElement")
    public JAXBElement<InputData> createInputData(InputData value) {
        return new JAXBElement<InputData>(_InputData_QNAME, InputData.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link KnowledgeSource }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "knowledgeSource", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "drgElement")
    public JAXBElement<KnowledgeSource> createKnowledgeSource(KnowledgeSource value) {
        return new JAXBElement<KnowledgeSource>(_KnowledgeSource_QNAME, KnowledgeSource.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Expression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "expression")
    public JAXBElement<Expression> createExpression(Expression value) {
        return new JAXBElement<Expression>(_Expression_QNAME, Expression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link ItemDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "itemDefinition", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "namedElement")
    public JAXBElement<ItemDefinition> createItemDefinition(ItemDefinition value) {
        return new JAXBElement<ItemDefinition>(_ItemDefinition_QNAME, ItemDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link LiteralExpression }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "literalExpression", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<LiteralExpression> createLiteralExpression(LiteralExpression value) {
        return new JAXBElement<LiteralExpression>(_LiteralExpression_QNAME, LiteralExpression.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Invocation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "invocation", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<Invocation> createInvocation(Invocation value) {
        return new JAXBElement<Invocation>(_Invocation_QNAME, Invocation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link InformationItem }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "informationItem", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "namedElement")
    public JAXBElement<InformationItem> createInformationItem(InformationItem value) {
        return new JAXBElement<InformationItem>(_InformationItem_QNAME, InformationItem.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecisionTable }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "decisionTable", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<DecisionTable> createDecisionTable(DecisionTable value) {
        return new JAXBElement<DecisionTable>(_DecisionTable_QNAME, DecisionTable.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Artifact }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "artifact", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "DMNElement")
    public JAXBElement<Artifact> createArtifact(Artifact value) {
        return new JAXBElement<Artifact>(_Artifact_QNAME, Artifact.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link TextAnnotation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "textAnnotation", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "artifact")
    public JAXBElement<TextAnnotation> createTextAnnotation(TextAnnotation value) {
        return new JAXBElement<TextAnnotation>(_TextAnnotation_QNAME, TextAnnotation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Association }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "association", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "artifact")
    public JAXBElement<Association> createAssociation(Association value) {
        return new JAXBElement<Association>(_Association_QNAME, Association.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Context }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "context", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<Context> createContext(Context value) {
        return new JAXBElement<Context>(_Context_QNAME, Context.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link FunctionDefinition }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "functionDefinition", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<FunctionDefinition> createFunctionDefinition(FunctionDefinition value) {
        return new JAXBElement<FunctionDefinition>(_FunctionDefinition_QNAME, FunctionDefinition.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link Relation }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "relation", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<Relation> createRelation(Relation value) {
        return new JAXBElement<Relation>(_Relation_QNAME, Relation.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link List }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "list", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "expression")
    public JAXBElement<List> createList(List value) {
        return new JAXBElement<List>(_List_QNAME, List.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link DecisionService }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "http://www.omg.org/spec/DMN/20130901", name = "decisionService", substitutionHeadNamespace = "http://www.omg.org/spec/DMN/20130901", substitutionHeadName = "namedElement")
    public JAXBElement<DecisionService> createDecisionService(DecisionService value) {
        return new JAXBElement<DecisionService>(_DecisionService_QNAME, DecisionService.class, null, value);
    }

}
