//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:30:38 PM GMT 
//


package io.onedecision.engine.decisions.model.dmn;

import java.io.Serializable;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;


/**
 * <p>Java class for tOutputClause complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tOutputClause"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20151101/dmn11.xsd}tDMNElement"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="outputValues" type="{http://www.omg.org/spec/DMN/20151101/dmn11.xsd}tUnaryTests" minOccurs="0"/&gt;
 *         &lt;element name="defaultOutputEntry" type="{http://www.omg.org/spec/DMN/20151101/dmn11.xsd}tLiteralExpression" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;attribute name="name" type="{http://www.w3.org/2001/XMLSchema}string" /&gt;
 *       &lt;attribute name="typeRef" type="{http://www.w3.org/2001/XMLSchema}QName" /&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tOutputClause", propOrder = {
    "outputValues",
    "defaultOutputEntry"
})
public class OutputClause extends DmnElement implements Serializable {

    private static final long serialVersionUID = -4640596164464458038L;
    protected UnaryTests outputValues;
    protected LiteralExpression defaultOutputEntry;
    @XmlAttribute(name = "name")
    protected String name;
    @XmlAttribute(name = "typeRef")
    protected QName typeRef;

    /**
     * Gets the value of the outputValues property.
     * 
     * @return
     *     possible object is
     *     {@link UnaryTests }
     *     
     */
    public UnaryTests getOutputValues() {
        return outputValues;
    }

    /**
     * Sets the value of the outputValues property.
     * 
     * @param value
     *     allowed object is
     *     {@link UnaryTests }
     *     
     */
    public void setOutputValues(UnaryTests value) {
        this.outputValues = value;
    }

    /**
     * Gets the value of the defaultOutputEntry property.
     * 
     * @return
     *     possible object is
     *     {@link LiteralExpression }
     *     
     */
    public LiteralExpression getDefaultOutputEntry() {
        return defaultOutputEntry;
    }

    /**
     * Sets the value of the defaultOutputEntry property.
     * 
     * @param value
     *     allowed object is
     *     {@link LiteralExpression }
     *     
     */
    public void setDefaultOutputEntry(LiteralExpression value) {
        this.defaultOutputEntry = value;
    }

    /**
     * Gets the value of the name property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getName() {
        return name;
    }

    /**
     * Sets the value of the name property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setName(String value) {
        this.name = value;
    }

    /**
     * Gets the value of the typeRef property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getTypeRef() {
        return typeRef;
    }

    /**
     * Sets the value of the typeRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setTypeRef(QName value) {
        this.typeRef = value;
    }

    public OutputClause withOutputValues(UnaryTests value) {
        setOutputValues(value);
        return this;
    }

    public OutputClause withDefaultOutputEntry(LiteralExpression value) {
        setDefaultOutputEntry(value);
        return this;
    }

    public OutputClause withName(String value) {
        setName(value);
        return this;
    }

    public OutputClause withTypeRef(QName value) {
        setTypeRef(value);
        return this;
    }

    @Override
    public OutputClause withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public OutputClause withExtensionElements(DmnElement.ExtensionElements value) {
        setExtensionElements(value);
        return this;
    }

    @Override
    public OutputClause withId(String value) {
        setId(value);
        return this;
    }

    @Override
    public OutputClause withLabel(String value) {
        setLabel(value);
        return this;
    }

}
