//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 09:06:03 PM BST 
//

@javax.xml.bind.annotation.XmlSchema(namespace = "http://www.omg.org/spec/DMN/20130901", elementFormDefault = javax.xml.bind.annotation.XmlNsForm.QUALIFIED)
package io.onedecision.engine.decisions.model.dmn;
