//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.06 at 04:59:26 PM BST 
//


package io.onedecision.engine.decisions.model.dmn;

import java.util.ArrayList;
import java.util.Collection;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tRelation complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tRelation"&gt;
 *   &lt;complexContent&gt;
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tExpression"&gt;
 *       &lt;sequence&gt;
 *         &lt;element name="column" type="{http://www.omg.org/spec/DMN/20130901}tContextEntry" maxOccurs="unbounded" minOccurs="0"/&gt;
 *         &lt;element ref="{http://www.omg.org/spec/DMN/20130901}List" maxOccurs="unbounded" minOccurs="0"/&gt;
 *       &lt;/sequence&gt;
 *       &lt;anyAttribute processContents='lax' namespace='##other'/&gt;
 *     &lt;/extension&gt;
 *   &lt;/complexContent&gt;
 * &lt;/complexType&gt;
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tRelation", propOrder = {
    "column",
    "list"
})
public class Relation
    extends Expression
{

    protected java.util.List<ContextEntry> column;
    @XmlElement(name = "List")
    protected java.util.List<io.onedecision.engine.decisions.model.dmn.List> list;

    /**
     * Gets the value of the column property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the column property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getColumn().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link ContextEntry }
     * 
     * 
     */
    public java.util.List<ContextEntry> getColumn() {
        if (column == null) {
            column = new ArrayList<ContextEntry>();
        }
        return this.column;
    }

    /**
     * Gets the value of the list property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the list property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getList().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link io.onedecision.engine.decisions.model.dmn.List }
     * 
     * 
     */
    public java.util.List<io.onedecision.engine.decisions.model.dmn.List> getList() {
        if (list == null) {
            list = new ArrayList<io.onedecision.engine.decisions.model.dmn.List>();
        }
        return this.list;
    }

    public Relation withColumn(ContextEntry... values) {
        if (values!= null) {
            for (ContextEntry value: values) {
                getColumn().add(value);
            }
        }
        return this;
    }

    public Relation withColumn(Collection<ContextEntry> values) {
        if (values!= null) {
            getColumn().addAll(values);
        }
        return this;
    }

    public Relation withList(io.onedecision.engine.decisions.model.dmn.List... values) {
        if (values!= null) {
            for (io.onedecision.engine.decisions.model.dmn.List value: values) {
                getList().add(value);
            }
        }
        return this;
    }

    public Relation withList(Collection<io.onedecision.engine.decisions.model.dmn.List> values) {
        if (values!= null) {
            getList().addAll(values);
        }
        return this;
    }

    @Override
    public Relation withDescription(String value) {
        setDescription(value);
        return this;
    }

    @Override
    public Relation withAny(Object... values) {
        if (values!= null) {
            for (Object value: values) {
                getAny().add(value);
            }
        }
        return this;
    }

    @Override
    public Relation withAny(Collection<Object> values) {
        if (values!= null) {
            getAny().addAll(values);
        }
        return this;
    }

    @Override
    public Relation withId(String value) {
        setId(value);
        return this;
    }

}
