//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.12.02 at 12:08:24 PM GMT 
//


package link.omny.decisions.model.dmn;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.namespace.QName;

import lombok.NoArgsConstructor;


/**
 * <p>Java class for tInformationItem complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType name="tInformationItem">
 *   &lt;complexContent>
 *     &lt;extension base="{http://www.omg.org/spec/DMN/20130901}tNamedDMNElement">
 *       &lt;sequence>
 *         &lt;element name="itemDefinition" type="{http://www.w3.org/2001/XMLSchema}QName" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;anyAttribute processContents='lax' namespace='##other'/>
 *     &lt;/extension>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "tInformationItem", propOrder = {
    "itemDefinition"
})
public class InformationItem extends NamedDmnElement {

    protected QName itemDefinition;

    /**
     * Gets the value of the itemDefinition property.
     * 
     * @return
     *     possible object is
     *     {@link QName }
     *     
     */
    public QName getItemDefinition() {
        return itemDefinition;
    }

    /**
     * Sets the value of the itemDefinition property.
     * 
     * @param value
     *     allowed object is
     *     {@link QName }
     *     
     */
    public void setItemDefinition(QName value) {
        this.itemDefinition = value;
    }

}
