//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.11 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2015.10.30 at 01:30:38 PM GMT 
//


package io.onedecision.engine.decisions.model.dmn;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for tDecisionTableOrientation.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="tDecisionTableOrientation"&gt;
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string"&gt;
 *     &lt;enumeration value="Rule-as-Row"/&gt;
 *     &lt;enumeration value="Rule-as-Column"/&gt;
 *     &lt;enumeration value="CrossTable"/&gt;
 *   &lt;/restriction&gt;
 * &lt;/simpleType&gt;
 * </pre>
 * 
 */
@XmlType(name = "tDecisionTableOrientation")
@XmlEnum
public enum DecisionTableOrientation {

    @XmlEnumValue("Rule-as-Row")
    RULE_AS_ROW("Rule-as-Row"),
    @XmlEnumValue("Rule-as-Column")
    RULE_AS_COLUMN("Rule-as-Column"),
    @XmlEnumValue("CrossTable")
    CROSS_TABLE("CrossTable");
    private final String value;

    DecisionTableOrientation(String v) {
        value = v;
    }

    public String value() {
        return value;
    }

    public static DecisionTableOrientation fromValue(String v) {
        for (DecisionTableOrientation c: DecisionTableOrientation.values()) {
            if (c.value.equalsIgnoreCase(v)) {
                return c;
            }
        }
        throw new IllegalArgumentException(v);
    }

}
